### ISSUE TITLE
Python 2.7 tests fail due to IPython upgrade

### ISSUE THREAD

**Issue by andreww** [alanfbaird/PyTASA#18]
The tests on TravisCI fail on Python 2.7 today because we need IPython, and (as of IPython 6.0, released yesterday) IPython needs Python3. We end up with the error recorded at https://travis-ci.org/alanfbaird/PyTASA/jobs/223865304

We have a few options:

1. Stop trying to support python2.7 (i.e. just specify that this needs python3). This would allow us to strip out the bits of compatibility stuff we already have (not much of that, to be honest) and mean that we would never need to depricate python2.7 in the future. However, this may cost us some users... If we do go down this route the guidance at http://www.python3statement.org/practicalities/ will be useful (and should be turned into an issue).

2. Fix this by specifying an older version of IPython. 5.x is a LTS release so this isOK for a few years. However, we don't currently list IPython in requirements.txt (it's just a prerequisite of Jupyter). This is probably possible but (a) a bit of a pain to do and to maintain and (b) would mean that people on python3 may end up downgrading stuff in order to run our code.

3. Implement a workaround in the testing. For example, we could select an alternative file to requirements.txt for the python2.7 tests. Probably easer for us to manage but this could leave us with complex installation instructions for users.

Not a great choice... I do wonder if I've missed something. Worth looking to see how Obspy handle this one.

Views? For now I'll just leave the 2.7 tests broken.

**Comment by alanfbaird** [comment]
Does Jupyter need to be included in requirements.txt? It's just used for examples so it's not really crucial for using the software. Alternatively, could we just list different requirements for different python versions like what's suggested here: http://stackoverflow.com/questions/19559247/requirements-txt-depending-on-python-version/33451105

I don't think we should drop support for python2.7, since that's what I use (though perhaps I should make the switch).

**Comment by andreww** [comment]
It's useful to check that the notebooks with examples actually run as part of the testing, so yes - we do need jupyter in there somewhere, at least for when we provision the test server. I didn't know we could do that in requirements.txt but that looks like a good approach. I'll try to take a look at this over the weekend.

You should probably make the switch. If you are using conda it's easy enough to create a new python3 environment and then move backwards and forwards as needed. The trick is to try and write any new code in python3 such that it still runs under python2.7 (I think it is easer to start this way than to try and update an existing python2.7 code base, at least at first).

**Comment by andreww** [comment]
It turns out that an up-to-date pip handles choosing the right version without a problem. Adding  pip upgrade pip to the travis file gives us an up-to-date pip on the python 2.7 travis instance and everything works again. The fix is merged onto master. @alanfbaird - it's probably worth rebasing anything you have in progress so we don't get unnecessary errors out of travis when it comes to merge other branches.
